-- JOIN
-- INNER / OUTER / CROSS

-- FOR INNER JOIN, THERE SHOULD BE AT LEAST 1 MATCH BETWEEN BOTH TABLES


-- LEFT OUTER JOIN

-- RIGHT OUTER JOIN

-- FULL OUTER JOIN

-- CROSS JOIN

USE AdventureWorks2016

CREATE TABLE MYEMPLOYEE
(EMPLOYEEID INT, FIRSTNAME VARCHAR(20), LASTNAME VARCHAR(20))

INSERT INTO MYEMPLOYEE VALUES (1, 'KIM', 'SANGWOO')
INSERT INTO MYEMPLOYEE VALUES (2, 'PARK', 'SEYOUNG')
INSERT INTO MYEMPLOYEE VALUES (3, 'CHOI', 'INHO')

SELECT * FROM MYEMPLOYEE

-- Inner Join

CREATE TABLE MYSALARY
(EMPLOYEEID INT, SALARY FLOAT)

INSERT INTO MYSALARY VALUES (1, '10000')
INSERT INTO MYSALARY VALUES (2, '8000')
INSERT INTO MYSALARY VALUES (3, '6000')

SELECT * FROM MYSALARY

--
SELECT A.FIRSTNAME, A.LASTNAME, B.SALARY FROM MYEMPLOYEE A INNER JOIN MYSALARY B 
ON A.EMPLOYEEID = B.EMPLOYEEID

-- Left outer join

CREATE TABLE MYPHONE (EMPLOYEEID INT, PHONENUMBER INT)

INSERT INTO MYPHONE VALUES (1, 01023456854)
INSERT INTO MYPHONE VALUES (2, 01063459745)

SELECT A.FIRSTNAME, A.LASTNAME, B.PHONENUMBER FROM MYEMPLOYEE A LEFT JOIN MYPHONE B
ON A.EMPLOYEEID = B.EMPLOYEEID

-- RIGHT JOINS

CREATE TABLE PARKING (EMPLOYEEID INT, PARKING_SPOT VARCHAR(10))

INSERT INTO PARKING VALUES (1, 'A1')
INSERT INTO PARKING VALUES (2, 'A2')

SELECT A.PARKING_SPOT, B.EMPLOYEEID, B.FIRSTNAME FROM PARKING A RIGHT JOIN MYEMPLOYEE B
ON A.EMPLOYEEID = B.EMPLOYEEID

-- FULL OUTER JOIN

--TRUNCATE TABLE MYCUSTOMER
CREATE TABLE MYCUSTOMER (CUSTOMERID INT, CUSTOMERNAME VARCHAR(20))
INSERT INTO MYCUSTOMER VALUES (1, 'RAKESH')
INSERT INTO MYCUSTOMER VALUES (3, 'JOHN')

-- TRUNCATE TABLE MYORDER
CREATE TABLE MYORDER (ORDERNUMBER INT, ORDERNAME VARCHAR(20), CUSTOMERID INT)
INSERT INTO MYORDER VALUES (1, 'ORDER1', 3)
INSERT INTO MYORDER VALUES (2, 'ORDER1', 2)
INSERT INTO MYORDER VALUES (3, 'ORDER1', 7)
INSERT INTO MYORDER VALUES (4, 'ORDER1', 8)

SELECT * FROM MYCUSTOMER
SELECT * FROM MYORDER

SELECT A.CUSTOMERID, A.CUSTOMERNAME, B.ORDERNUMBER, B.ORDERNAME FROM MYCUSTOMER A FULL OUTER JOIN MYORDER B
ON A.CUSTOMERID=B.CUSTOMERID

-- CROSS JOIN
SELECT * FROM MYCUSTOMER CROSS JOIN MYSALARY